<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'update.listener' shared service.

include_once $this->targetDirs[3].'\\src\\UserBundle\\Listener\\LogListener.php';

return $this->services['update.listener'] = new \UserBundle\Listener\LogListener(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
