services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    update.listener:
        class: UserBundle\Listener\LogListener
        arguments:
          - '@logger'
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
    remove.listener:
            class: UserBundle\Listener\LogListener
            arguments:
              - '@logger'
            tags:
                - { name: doctrine.event_listener, event: postRemove }