<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4thqfgp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4thqfgp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4thqfgp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4thqfgp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4thqfgp\appDevDebugProjectContainer([
    'container.build_hash' => '4thqfgp',
    'container.build_id' => '5a6ea539',
    'container.build_time' => 1576709957,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4thqfgp');
